
asciidoc:
    attributes:
      source-highlighter: coderay


profiles:
  production:
    base_url: http://undertow.io
    deploy:
      host: filemgmt.jboss.org
      path: /www_htdocs/undertow
      username: undertow